version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8082:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
    restart: always

  Apache:
    image: httpd:latest
    container_name: apache_web
    ports:
      - "8081:80"
    volumes:
      - ./Apache:/usr/local/apache2/htdocs/
    restart: always

